### PR TITLE
Add 'app' name to object to map correctly to <app>

### PR DESCRIPTION
**Pull request by diverted247**
Seen errors with this after the next component is added.

### CODE REVIEW

**Comment by yyx990803** [comment]
How did you add the next component? This shouldn't be the cause of the issue.

**Comment by diverted247** [comment]
Might be just me but the object notation is odd there (yet works for single
items)...
components:{ App } vs components:{ app:App }

Most object literals are denoted by name. In learning vue this was a point
of confusion as the "components" object was denoting element to component
mapping.

In later Vueify components, this pattern becomes clearer when the
"components" name is the mapping based on imports...

<template>
    <toolbar></toolbar>
</template>

<script>
    import Toolbar from './components/Toolbar.vue';
export default {
        data() {
            return {};
        },
        components: {
            toolbar:Toolbar
        }
    }
</script>

The single object {App} was confusing as:
1. Element html reads <app> not <App>
2. No name mapping in the components app:App
3. Later uses of this pattern are different from main.js to use inside .vue
files.

Ted :)

**Comment by diverted247** [comment]
The other case here is that some js linters flag the single element object
notion as an error. Here JSLint is flagging it as invalid.

https://www.dropbox.com/s/zjrcam4shxcclal/Screenshot%202016-01-05%2010.55.18.png?dl=0

**Comment by yyx990803** [comment]
This is actually [ES6 Object literal shorthand syntax](https://github.com/lukehoban/es6features#enhanced-object-literals), so it only works if the JavaScript is transpiled via Babel. JSLint is pretty out of date and cannot handle ES6, you should checkout [ESLint](http://eslint.org/), which is modern, better maintained and configurable.

**Comment by diverted247** [comment]
This makes sense as a ES2015 feature but it was a source of confusion for
me and will be for others.

My 2 cents,

Ted :)

**Pull request closed without merging**
